### ISSUE TITLE
[FEATURE REQUEST]: DataFrame API Completeness for Spark 2.4.x

### ISSUE THREAD

**Issue by suhsteve** [dotnet/spark#621]
### DataFrame
* [ ] `python` def toJSON(self, use_unicode=True)
* [ ] `python` ~~def registerTempTable(self, name)~~`Deprecated` in 2.0
* [ ] `python` ~~def foreach(self, f)~~ Unsupported `RDD`
* [ ] `python` ~~def foreachPartition(self, f)~~ Unsupported `RDD`
* [ ] `python` ~~def unionAll(self, other)~~ `Deprecated` in 2.0
* [ ] `python` ~~def subtract(self, other):~~   `python` names this `subtract` instead of `except`
* [ ] `python` ~~def dropna(self, how='any', thresh=None, subset=None)~~ Supported by calling `DataFrameNaFunctions.Drop(...)`
* [ ] `python` ~~def fillna(self, value, subset=None)~~ Supported by calling `DataFrameNaFunctions.Fill(...)`
* [x] `csharp` public DataFrame Persist(StorageLevel storageLevel) (#623)
* [x] `csharp` public StorageLevel StorageLevel() (#623)
* [x] `csharp` public IEnumerable<Tuple<string, string>> DTypes() (#635)
* [x] `csharp` public Column this[string columnName]
* [x] `csharp` public DataFrame ToDF()
* [x] `csharp` public DataFrame ToDF(params string[] colNames)
* [x] `csharp` public StructType Schema()
* [x] `csharp` public void PrintSchema()
* [x] `csharp` public void Explain(bool extended = false)
* [x] `csharp` public IReadOnlyList<string> Columns()
* [x] `csharp` public bool IsLocal()
* [x] `csharp` public bool IsEmpty()
* [x] `csharp` public bool IsStreaming()
* [x] `csharp` public DataFrame Checkpoint(bool eager = true)
* [x] `csharp` public DataFrame LocalCheckpoint(bool eager = true)
* [x] `csharp` public DataFrame WithWatermark(string eventTime, string delayThreshold)
* [x] `csharp` public void Show(int numRows = 20, int truncate = 20, bool vertical = false)
* [x] `csharp` public DataFrameNaFunctions Na()
* [x] `csharp` public DataFrameStatFunctions Stat()
* [x] `csharp` public DataFrame Join(DataFrame right)
* [x] `csharp` public DataFrame Join(DataFrame right, string usingColumn)
* [x] `csharp` public DataFrame Join(
* [x] `csharp` public DataFrame Join(DataFrame right, Column joinExpr, string joinType = "inner")
* [x] `csharp` public DataFrame CrossJoin(DataFrame right)
* [x] `csharp` public DataFrame SortWithinPartitions(string column, params string[] columns)
* [x] `csharp` public DataFrame SortWithinPartitions(params Column[] columns)
* [x] `csharp` public DataFrame Sort(string column, params string[] columns)
* [x] `csharp` public DataFrame Sort(params Column[] columns)
* [x] `csharp` public DataFrame OrderBy(string column, params string[] columns)
* [x] `csharp` public DataFrame OrderBy(params Column[] columns)
* [x] `csharp` public DataFrame Hint(string name, object[] parameters = null)
* [x] `csharp` public Column Col(string colName)
* [x] `csharp` public Column ColRegex(string colName)
* [x] `csharp` public DataFrame As(string alias)
* [x] `csharp` public DataFrame Alias(string alias)
* [x] `csharp` public DataFrame Select(params Column[] columns)
* [x] `csharp` public DataFrame Select(string column, params string[] columns)
* [x] `csharp` public DataFrame SelectExpr(params string[] expressions)
* [x] `csharp` public DataFrame Filter(Column condition)
* [x] `csharp` public DataFrame Filter(string conditionExpr)
* [x] `csharp` public DataFrame Where(Column condition)
* [x] `csharp` public DataFrame Where(string conditionExpr)
* [x] `csharp` public RelationalGroupedDataset GroupBy(params Column[] columns)
* [x] `csharp` public RelationalGroupedDataset GroupBy(string column, params string[] columns)
* [x] `csharp` public RelationalGroupedDataset Rollup(params Column[] columns)
* [x] `csharp` public RelationalGroupedDataset Rollup(string column, params string[] columns)
* [x] `csharp` public RelationalGroupedDataset Cube(params Column[] columns)
* [x] `csharp` public RelationalGroupedDataset Cube(string column, params string[] columns)
* [x] `csharp` public DataFrame Agg(Column expr, params Column[] exprs)
* [x] `csharp` public DataFrame Limit(int n)
* [x] `csharp` public DataFrame Union(DataFrame other)
* [x] `csharp` public DataFrame UnionByName(DataFrame other)
* [x] `csharp` public DataFrame Intersect(DataFrame other)
* [x] `csharp` public DataFrame IntersectAll(DataFrame other)
* [x] `csharp` public DataFrame Except(DataFrame other)
* [x] `csharp` public DataFrame ExceptAll(DataFrame other)
* [x] `csharp` public DataFrame Sample(
* [x] `csharp` public DataFrame[] RandomSplit(double[] weights, long? seed = null)
* [x] `csharp` public DataFrame WithColumn(string colName, Column col)
* [x] `csharp` public DataFrame WithColumnRenamed(string existingName, string newName)
* [x] `csharp` public DataFrame Drop(params string[] colNames)
* [x] `csharp` public DataFrame Drop(Column col)
* [x] `csharp` public DataFrame DropDuplicates()
* [x] `csharp` public DataFrame DropDuplicates(string col, params string[] cols)
* [x] `csharp` public DataFrame Describe(params string[] cols)
* [x] `csharp` public DataFrame Summary(params string[] statistics)
* [x] `csharp` public IEnumerable<Row> Head(int n)
* [x] `csharp` public Row Head()
* [x] `csharp` public Row First()
* [x] `csharp` public IEnumerable<Row> Take(int n)
* [x] `csharp` public IEnumerable<Row> Collect()
* [x] `csharp` public IEnumerable<Row> ToLocalIterator()
* [x] `csharp` public long Count()
* [x] `csharp` public DataFrame Repartition(int numPartitions)
* [x] `csharp` public DataFrame Repartition(int numPartitions, params Column[] partitionExprs)
* [x] `csharp` public DataFrame Repartition(params Column[] partitionExprs)
* [x] `csharp` public DataFrame RepartitionByRange(int numPartitions, params Column[] partitionExprs)
* [x] `csharp` public DataFrame RepartitionByRange(params Column[] partitionExprs)
* [x] `csharp` public DataFrame Coalesce(int numPartitions)
* [x] `csharp` public DataFrame Distinct()
* [x] `csharp` public DataFrame Persist()
* [x] `csharp` public DataFrame Cache()
* [x] `csharp` public DataFrame Unpersist(bool blocking = false)
* [x] `csharp` public void CreateTempView(string viewName)
* [x] `csharp` public void CreateOrReplaceTempView(string viewName)
* [x] `csharp` public void CreateGlobalTempView(string viewName)
* [x] `csharp` public void CreateOrReplaceGlobalTempView(string viewName)
* [x] `csharp` public DataFrameWriter Write()
* [x] `csharp` public DataStreamWriter WriteStream()

### RelationalGroupedDataset
* [x] `csharp` public RelationalGroupedDataset Pivot(string pivotColumn) (#598)
* [x] `csharp` public RelationalGroupedDataset Pivot(string pivotColumn, IEnumerable<object> values) (#642)
* [x] `csharp` public RelationalGroupedDataset Pivot(Column pivotColumn) (#598)
* [x] `csharp` public RelationalGroupedDataset Pivot(Column pivotColumn, IEnumerable<object> values) (#642)
* [x] `csharp` `python` def pivot(self, pivot_col, values=None)
* [x] `csharp` public DataFrame Agg(Column expr, params Column[] exprs)
* [x] `csharp` public DataFrame Count()
* [x] `csharp` public DataFrame Mean(params string[] colNames)
* [x] `csharp` public DataFrame Max(params string[] colNames)
* [x] `csharp` public DataFrame Avg(params string[] colNames)
* [x] `csharp` public DataFrame Min(params string[] colNames)
* [x] `csharp` public DataFrame Sum(params string[] colNames)

### DataFrameStatFunctions
* [x] `csharp` public double[] ApproxQuantile(string columnName, IEnumerable<double> probabilities, double relativeError)
* [x] `csharp` public double Cov(string colName1, string colName2)
* [x] `csharp` public double Corr(string colName1, string colName2, string method)
* [x] `csharp` public double Corr(string colName1, string colName2)
* [x] `csharp` public DataFrame Crosstab(string colName1, string colName2)
* [x] `csharp` public DataFrame FreqItems(IEnumerable<string> columnNames, double support)
* [x] `csharp` public DataFrame FreqItems(IEnumerable<string> columnNames)
* [x] `csharp` public DataFrame SampleBy<T>(string columnName, IDictionary<T, double> fractions, long seed)

### DataFrameNaFunctions
* [x] `csharp` public DataFrame Drop()
* [x] `csharp` public DataFrame Drop(string how)
* [x] `csharp` public DataFrame Drop(IEnumerable<string> columnNames)
* [x] `csharp` public DataFrame Drop(string how, IEnumerable<string> columnNames)
* [x] `csharp` public DataFrame Drop(int minNonNulls)
* [x] `csharp` public DataFrame Drop(int minNonNulls, IEnumerable<string> columnNames)
* [x] `csharp` public DataFrame Fill(long value)
* [x] `csharp` public DataFrame Fill(double value)
* [x] `csharp` public DataFrame Fill(string value)
* [x] `csharp` public DataFrame Fill(long value, IEnumerable<string> columnNames)
* [x] `csharp` public DataFrame Fill(double value, IEnumerable<string> columnNames)
* [x] `csharp` public DataFrame Fill(string value, IEnumerable<string> columnNames)
* [x] `csharp` public DataFrame Fill(bool value)
* [x] `csharp` public DataFrame Fill(bool value, IEnumerable<string> columnNames)
* [x] `csharp` public DataFrame Fill(IDictionary<string, int> valueMap)
* [x] `csharp` public DataFrame Fill(IDictionary<string, long> valueMap)
* [x] `csharp` public DataFrame Fill(IDictionary<string, double> valueMap)
* [x] `csharp` public DataFrame Fill(IDictionary<string, string> valueMap)
* [x] `csharp` public DataFrame Fill(IDictionary<string, bool> valueMap)
* [x] `csharp` public DataFrame Replace(string columnName, IDictionary<double, double> replacement)
* [x] `csharp` public DataFrame Replace(string columnName, IDictionary<bool, bool> replacement)
* [x] `csharp` public DataFrame Replace(string columnName, IDictionary<string, string> replacement)
* [x] `csharp` public DataFrame Replace(IEnumerable<string> columnNames, IDictionary<double, double> replacement)
* [x] `csharp` public DataFrame Replace(IEnumerable<string> columnNames, IDictionary<bool, bool> replacement)
* [x] `csharp` public DataFrame Replace(IEnumerable<string> columnNames, IDictionary<string, string> replacement)

### Functions
* [x] `csharp` public static Column Column(string columnName)
* [x] `csharp` public static Column Col(string columnName)
* [x] `csharp` public static Column Lit(object literal)
* [x] `csharp` public static Column Asc(string columnName)
* [x] `csharp` public static Column AscNullsFirst(string columnName)
* [x] `csharp` public static Column AscNullsLast(string columnName)
* [x] `csharp` public static Column Desc(string columnName)
* [x] `csharp` public static Column DescNullsFirst(string columnName)
* [x] `csharp` public static Column DescNullsLast(string columnName)
* [x] `csharp` public static Column ApproxCountDistinct(Column column)
* [x] `csharp` public static Column ApproxCountDistinct(string columnName)
* [x] `csharp` public static Column ApproxCountDistinct(Column column, double rsd)
* [x] `csharp` public static Column ApproxCountDistinct(string columnName, double rsd)
* [x] `csharp` public static Column Avg(Column column)
* [x] `csharp` public static Column Avg(string columnName)
* [x] `csharp` public static Column CollectList(Column column)
* [x] `csharp` public static Column CollectList(string columnName)
* [x] `csharp` public static Column CollectSet(Column column)
* [x] `csharp` public static Column CollectSet(string columnName)
* [x] `csharp` public static Column Corr(Column column1, Column column2)
* [x] `csharp` public static Column Corr(string columnName1, string columnName2)
* [x] `csharp` public static Column Count(Column column)
* [x] `csharp` public static Column Count(string columnName)
* [x] `csharp` public static Column CountDistinct(Column column, params Column[] columns)
* [x] `csharp` public static Column CountDistinct(string columnName, params string[] columnNames)
* [x] `csharp` public static Column CovarPop(Column column1, Column column2)
* [x] `csharp` public static Column CovarPop(string columnName1, string columnName2)
* [x] `csharp` public static Column CovarSamp(Column column1, Column column2)
* [x] `csharp` public static Column CovarSamp(string columnName1, string columnName2)
* [x] `csharp` public static Column First(Column column, bool ignoreNulls = false)
* [x] `csharp` public static Column First(string columnName, bool ignoreNulls = false)
* [x] `csharp` public static Column Grouping(Column column)
* [x] `csharp` public static Column Grouping(string columnName)
* [x] `csharp` public static Column GroupingId(params Column[] columns)
* [x] `csharp` public static Column GroupingId(string columnName, params string[] columnNames)
* [x] `csharp` public static Column Kurtosis(Column column)
* [x] `csharp` public static Column Kurtosis(string columnName)
* [x] `csharp` public static Column Last(Column column, bool ignoreNulls = false)
* [x] `csharp` public static Column Last(string columnName, bool ignoreNulls = false)
* [x] `csharp` public static Column Max(Column column)
* [x] `csharp` public static Column Max(string columnName)
* [x] `csharp` public static Column Mean(Column column)
* [x] `csharp` public static Column Mean(string columnName)
* [x] `csharp` public static Column Min(Column column)
* [x] `csharp` public static Column Min(string columnName)
* [x] `csharp` public static Column Skewness(Column column)
* [x] `csharp` public static Column Skewness(string columnName)
* [x] `csharp` public static Column Stddev(Column column)
* [x] `csharp` public static Column Stddev(string columnName)
* [x] `csharp` public static Column StddevSamp(Column column)
* [x] `csharp` public static Column StddevSamp(string columnName)
* [x] `csharp` public static Column StddevPop(Column column)
* [x] `csharp` public static Column StddevPop(string columnName)
* [x] `csharp` public static Column Sum(Column column)
* [x] `csharp` public static Column Sum(string columnName)
* [x] `csharp` public static Column SumDistinct(Column column)
* [x] `csharp` public static Column SumDistinct(string columnName)
* [x] `csharp` public static Column Variance(Column column)
* [x] `csharp` public static Column Variance(string columnName)
* [x] `csharp` public static Column VarSamp(Column column)
* [x] `csharp` public static Column VarSamp(string columnName)
* [x] `csharp` public static Column VarPop(Column column)
* [x] `csharp` public static Column VarPop(string columnName)
* [x] `csharp` public static Column UnboundedPreceding()
* [x] `csharp` public static Column UnboundedFollowing()
* [x] `csharp` public static Column CurrentRow()
* [x] `csharp` public static Column CumeDist()
* [x] `csharp` public static Column DenseRank()
* [x] `csharp` public static Column Lag(Column column, int offset, object defaultValue = null)
* [x] `csharp` public static Column Lag(string columnName, int offset, object defaultValue = null)
* [x] `csharp` public static Column Lead(Column column, int offset, object defaultValue = null)
* [x] `csharp` public static Column Lead(string columnName, int offset, object defaultValue = null)
* [x] `csharp` public static Column Ntile(int n)
* [x] `csharp` public static Column PercentRank()
* [x] `csharp` public static Column Rank()
* [x] `csharp` public static Column RowNumber()
* [x] `csharp` public static Column Abs(Column column)
* [x] `csharp` public static Column Array(params Column[] columns)
* [x] `csharp` public static Column Array(string columnName, params string[] columnNames)
* [x] `csharp` public static Column Map(params Column[] columns)
* [x] `csharp` public static Column MapFromArrays(Column key, Column values)
* [x] `csharp` public static DataFrame Broadcast(DataFrame df)
* [x] `csharp` public static Column Coalesce(params Column[] columns)
* [x] `csharp` public static Column InputFileName()
* [x] `csharp` public static Column IsNaN(Column column)
* [x] `csharp` public static Column IsNull(Column column)
* [x] `csharp` public static Column MonotonicallyIncreasingId()
* [x] `csharp` public static Column NaNvl(Column column1, Column column2)
* [x] `csharp` public static Column Negate(Column column)
* [x] `csharp` public static Column Not(Column column)
* [x] `csharp` public static Column Rand(long seed)
* [x] `csharp` public static Column Rand()
* [x] `csharp` public static Column Randn(long seed)
* [x] `csharp` public static Column Randn()
* [x] `csharp` public static Column SparkPartitionId()
* [x] `csharp` public static Column Sqrt(Column column)
* [x] `csharp` public static Column Sqrt(string columnName)
* [x] `csharp` public static Column Struct(params Column[] columns)
* [x] `csharp` public static Column Struct(string columnName, params string[] columnNames)
* [x] `csharp` public static Column When(Column condition, object value)
* [x] `csharp` public static Column BitwiseNOT(Column column)
* [x] `csharp` public static Column Expr(string expr)
* [x] `csharp` public static Column Acos(Column column)
* [x] `csharp` public static Column Acos(string columnName)
* [x] `csharp` public static Column Asin(Column column)
* [x] `csharp` public static Column Asin(string columnName)
* [x] `csharp` public static Column Atan(Column column)
* [x] `csharp` public static Column Atan(string columnName)
* [x] `csharp` public static Column Atan2(Column y, Column x)
* [x] `csharp` public static Column Atan2(Column y, string xName)
* [x] `csharp` public static Column Atan2(string yName, Column x)
* [x] `csharp` public static Column Atan2(string yName, string xName)
* [x] `csharp` public static Column Atan2(Column y, double xValue)
* [x] `csharp` public static Column Atan2(string yName, double xValue)
* [x] `csharp` public static Column Atan2(double yValue, Column x)
* [x] `csharp` public static Column Atan2(double yValue, string xName)
* [x] `csharp` public static Column Bin(Column column)
* [x] `csharp` public static Column Bin(string columnName)
* [x] `csharp` public static Column Cbrt(Column column)
* [x] `csharp` public static Column Cbrt(string columnName)
* [x] `csharp` public static Column Ceil(Column column)
* [x] `csharp` public static Column Ceil(string columnName)
* [x] `csharp` public static Column Conv(Column column, int fromBase, int toBase)
* [x] `csharp` public static Column Cos(Column column)
* [x] `csharp` public static Column Cos(string columnName)
* [x] `csharp` public static Column Cosh(Column column)
* [x] `csharp` public static Column Cosh(string columnName)
* [x] `csharp` public static Column Exp(Column column)
* [x] `csharp` public static Column Exp(string columnName)
* [x] `csharp` public static Column Expm1(Column column)
* [x] `csharp` public static Column Expm1(string columnName)
* [x] `csharp` public static Column Factorial(Column column)
* [x] `csharp` public static Column Floor(Column column)
* [x] `csharp` public static Column Floor(string columnName)
* [x] `csharp` public static Column Greatest(params Column[] columns)
* [x] `csharp` public static Column Greatest(string columnName, params string[] columnNames)
* [x] `csharp` public static Column Hex(Column column)
* [x] `csharp` public static Column Unhex(Column column)
* [x] `csharp` public static Column Hypot(Column left, Column right)
* [x] `csharp` public static Column Hypot(Column left, string rightName)
* [x] `csharp` public static Column Hypot(string leftName, Column right)
* [x] `csharp` public static Column Hypot(string leftName, string rightName)
* [x] `csharp` public static Column Hypot(Column left, double right)
* [x] `csharp` public static Column Hypot(string leftName, double right)
* [x] `csharp` public static Column Hypot(double left, Column right)
* [x] `csharp` public static Column Hypot(double left, string rightName)
* [x] `csharp` public static Column Least(params Column[] columns)
* [x] `csharp` public static Column Least(string columnName, params string[] columnNames)
* [x] `csharp` public static Column Log(Column column)
* [x] `csharp` public static Column Log(string columnName)
* [x] `csharp` public static Column Log(double logBase, Column column)
* [x] `csharp` public static Column Log(double logBase, string columnName)
* [x] `csharp` public static Column Log10(Column column)
* [x] `csharp` public static Column Log10(string columnName)
* [x] `csharp` public static Column Log1p(Column column)
* [x] `csharp` public static Column Log1p(string columnName)
* [x] `csharp` public static Column Log2(Column column)
* [x] `csharp` public static Column Log2(string columnName)
* [x] `csharp` public static Column Pow(Column left, Column right)
* [x] `csharp` public static Column Pow(Column left, string rightName)
* [x] `csharp` public static Column Pow(string leftName, Column right)
* [x] `csharp` public static Column Pow(string leftName, string rightName)
* [x] `csharp` public static Column Pow(Column left, double right)
* [x] `csharp` public static Column Pow(string leftName, double right)
* [x] `csharp` public static Column Pow(double left, Column right)
* [x] `csharp` public static Column Pow(double left, string rightName)
* [x] `csharp` public static Column Pmod(Column left, Column right)
* [x] `csharp` public static Column Rint(Column column)
* [x] `csharp` public static Column Rint(string columnName)
* [x] `csharp` public static Column Round(Column column)
* [x] `csharp` public static Column Round(Column column, int scale)
* [x] `csharp` public static Column Bround(Column column)
* [x] `csharp` public static Column Bround(Column column, int scale)
* [x] `csharp` public static Column ShiftLeft(Column column, int numBits)
* [x] `csharp` public static Column ShiftRight(Column column, int numBits)
* [x] `csharp` public static Column ShiftRightUnsigned(Column column, int numBits)
* [x] `csharp` public static Column Signum(Column column)
* [x] `csharp` public static Column Signum(string columnName)
* [x] `csharp` public static Column Sin(Column column)
* [x] `csharp` public static Column Sin(string columnName)
* [x] `csharp` public static Column Sinh(Column column)
* [x] `csharp` public static Column Sinh(string columnName)
* [x] `csharp` public static Column Tan(Column column)
* [x] `csharp` public static Column Tan(string columnName)
* [x] `csharp` public static Column Tanh(Column column)
* [x] `csharp` public static Column Tanh(string columnName)
* [x] `csharp` public static Column Degrees(Column column)
* [x] `csharp` public static Column Degrees(string columnName)
* [x] `csharp` public static Column Radians(Column column)
* [x] `csharp` public static Column Radians(string columnName)
* [x] `csharp` public static Column Md5(Column column)
* [x] `csharp` public static Column Sha1(Column column)
* [x] `csharp` public static Column Sha2(Column column, int numBits)
* [x] `csharp` public static Column Crc32(Column column)
* [x] `csharp` public static Column Hash(params Column[] columns)
* [x] `csharp` public static Column Ascii(Column column)
* [x] `csharp` public static Column Base64(Column column)
* [x] `csharp` public static Column ConcatWs(string sep, params Column[] columns)
* [x] `csharp` public static Column Decode(Column column, string charset)
* [x] `csharp` public static Column Encode(Column column, string charset)
* [x] `csharp` public static Column FormatNumber(Column column, int d)
* [x] `csharp` public static Column FormatString(string format, params Column[] columns)
* [x] `csharp` public static Column InitCap(Column column)
* [x] `csharp` public static Column Instr(Column column, string substring)
* [x] `csharp` public static Column Length(Column column)
* [x] `csharp` public static Column Lower(Column column)
* [x] `csharp` public static Column Levenshtein(Column left, Column right)
* [x] `csharp` public static Column Locate(string substring, Column column)
* [x] `csharp` public static Column Locate(string substring, Column column, int pos)
* [x] `csharp` public static Column Lpad(Column column, int len, string pad)
* [x] `csharp` public static Column Ltrim(Column column)
* [x] `csharp` public static Column Ltrim(Column column, string trimString)
* [x] `csharp` public static Column RegexpExtract(Column column, string exp, int groupIdx)
* [x] `csharp` public static Column RegexpReplace(Column column, string pattern, string replacement)
* [x] `csharp` public static Column RegexpReplace(Column column, Column pattern, Column replacement)
* [x] `csharp` public static Column Unbase64(Column column)
* [x] `csharp` public static Column Rpad(Column column, int len, string pad)
* [x] `csharp` public static Column Repeat(Column column, int n)
* [x] `csharp` public static Column Rtrim(Column column)
* [x] `csharp` public static Column Rtrim(Column column, string trimString)
* [x] `csharp` public static Column Soundex(Column column)
* [x] `csharp` public static Column Split(Column column, string pattern)
* [x] `csharp` public static Column Substring(Column column, int pos, int len)
* [x] `csharp` public static Column SubstringIndex(Column column, string delimiter, int count)
* [x] `csharp` public static Column Translate(Column column, string matchingString, string replaceString)
* [x] `csharp` public static Column Trim(Column column)
* [x] `csharp` public static Column Trim(Column column, string trimString)
* [x] `csharp` public static Column Upper(Column column)
* [x] `csharp` public static Column AddMonths(Column startDate, int numMonths)
* [x] `csharp` public static Column CurrentDate()
* [x] `csharp` public static Column CurrentTimestamp()
* [x] `csharp` public static Column DateFormat(Column dateExpr, string format)
* [x] `csharp` public static Column DateAdd(Column start, int days)
* [x] `csharp` public static Column DateSub(Column start, int days)
* [x] `csharp` public static Column DateDiff(Column end, Column start)
* [x] `csharp` public static Column Year(Column column)
* [x] `csharp` public static Column Quarter(Column column)
* [x] `csharp` public static Column Month(Column column)
* [x] `csharp` public static Column DayOfWeek(Column column)
* [x] `csharp` public static Column DayOfMonth(Column column)
* [x] `csharp` public static Column DayOfYear(Column column)
* [x] `csharp` public static Column Hour(Column column)
* [x] `csharp` public static Column LastDay(Column column)
* [x] `csharp` public static Column Minute(Column column)
* [x] `csharp` public static Column MonthsBetween(Column end, Column start)
* [x] `csharp` public static Column MonthsBetween(Column end, Column start, bool roundOff)
* [x] `csharp` public static Column NextDay(Column date, string dayOfWeek)
* [x] `csharp` public static Column Second(Column column)
* [x] `csharp` public static Column WeekOfYear(Column column)
* [x] `csharp` public static Column FromUnixTime(Column column)
* [x] `csharp` public static Column FromUnixTime(Column column, string format)
* [x] `csharp` public static Column UnixTimestamp()
* [x] `csharp` public static Column UnixTimestamp(Column column)
* [x] `csharp` public static Column UnixTimestamp(Column column, string format)
* [x] `csharp` public static Column ToTimestamp(Column column)
* [x] `csharp` public static Column ToTimestamp(Column column, string format)
* [x] `csharp` public static Column ToDate(Column column)
* [x] `csharp` public static Column ToDate(Column column, string format)
* [x] `csharp` public static Column Trunc(Column column, string format)
* [x] `csharp` public static Column DateTrunc(string format, Column column)
* [x] `csharp` public static Column FromUtcTimestamp(Column column, string tz)
* [x] `csharp` public static Column FromUtcTimestamp(Column column, Column tz)
* [x] `csharp` public static Column ToUtcTimestamp(Column column, string tz)
* [x] `csharp` public static Column ToUtcTimestamp(Column column, Column tz)
* [x] `csharp` public static Column Window(Column column, string windowDuration, string slideDuration, string startTime)
* [x] `csharp` public static Column Window(Column column, string windowDuration, string slideDuration)
* [x] `csharp` public static Column Window(Column column, string windowDuration)
* [x] `csharp` public static Column ArrayContains(Column column, object value)
* [x] `csharp` public static Column ArraysOverlap(Column a1, Column a2)
* [x] `csharp` public static Column Slice(Column column, int start, int length)
* [x] `csharp` public static Column ArrayJoin(Column column, string delimiter, string nullReplacement)
* [x] `csharp` public static Column ArrayJoin(Column column, string delimiter)
* [x] `csharp` public static Column Concat(params Column[] columns)
* [x] `csharp` public static Column ArrayPosition(Column column, object value)
* [x] `csharp` public static Column ElementAt(Column column, object value)
* [x] `csharp` public static Column ArraySort(Column column)
* [x] `csharp` public static Column ArrayRemove(Column column, object element)
* [x] `csharp` public static Column ArrayDistinct(Column column)
* [x] `csharp` public static Column ArrayIntersect(Column col1, Column col2)
* [x] `csharp` public static Column ArrayUnion(Column col1, Column col2)
* [x] `csharp` public static Column ArrayExcept(Column col1, Column col2)
* [x] `csharp` public static Column Explode(Column column)
* [x] `csharp` public static Column ExplodeOuter(Column column)
* [x] `csharp` public static Column PosExplode(Column column)
* [x] `csharp` public static Column PosExplodeOuter(Column column)
* [x] `csharp` public static Column GetJsonObject(Column column, string path)
* [x] `csharp` public static Column JsonTuple(Column column, params string[] fields)
* [x] `csharp` public static Column FromJson(Column column, string schema, Dictionary<string, string> options = null)
* [x] `csharp` public static Column FromJson(Column column, Column schema, Dictionary<string, string> options = null)
* [x] `csharp` public static Column SchemaOfJson(string json)
* [x] `csharp` public static Column SchemaOfJson(Column json)
* [x] `csharp` public static Column ToJson(Column column, Dictionary<string, string> options = null)
* [x] `csharp` public static Column Size(Column column)
* [x] `csharp` public static Column SortArray(Column column, bool asc = true)
* [x] `csharp` public static Column ArrayMin(Column column)
* [x] `csharp` public static Column ArrayMax(Column column)
* [x] `csharp` public static Column Shuffle(Column column)
* [x] `csharp` public static Column Reverse(Column column)
* [x] `csharp` public static Column Flatten(Column column)
* [x] `csharp` public static Column Sequence(Column start, Column stop, Column step)
* [x] `csharp` public static Column Sequence(Column start, Column stop)
* [x] `csharp` public static Column ArrayRepeat(Column left, Column right)
* [x] `csharp` public static Column ArrayRepeat(Column left, int count)
* [x] `csharp` public static Column MapKeys(Column column)
* [x] `csharp` public static Column MapValues(Column column)
* [x] `csharp` public static Column MapFromEntries(Column column)
* [x] `csharp` public static Column ArraysZip(params Column[] columns)
* [x] `csharp` public static Column MapConcat(params Column[] columns)
* [x] `csharp` public static Func<Column> Udf<TResult>(Func<TResult> udf)
* [x] `csharp` public static Func<Column, Column> Udf<T, TResult>(Func<T, TResult> udf)
* [x] `csharp` public static Func<Column, Column, Column> Udf<T1, T2, TResult>(Func<T1, T2, TResult> udf)
* [x] `csharp` public static Func<Column, Column, Column, Column> Udf<T1, T2, T3, TResult>(...
* [x] `csharp` public static Func<Column, Column, Column, Column, Column> Udf<T1, T2, T3, T4, TResult>(...
* [x] `csharp` public static Func<Column, Column, Column, Column, Column, Column> Udf<T1, T2, T3, T4, T5, TResult>(...
* [x] `csharp` public static Func<Column, Column, Column, Column, Column, Column, Column> Udf<T1, T2, T3, T4, T5, T6, TResult>(...
* [x] `csharp` public static Func<Column, Column, Column, Column, Column, Column, Column, Column> Udf<T1, T2, T3, T4, T5, T6, T7, TResult>(...
* [x] `csharp` public static Func<Column, Column, Column, Column, Column, Column, Column, Column, Column> Udf<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(...
* [x] `csharp` public static Func<Column, Column, Column, Column, Column, Column, Column, Column, Column, Column> Udf<T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>(...
* [x] `csharp` public static Func<Column, Column, Column, Column, Column, Column, Column, Column, Column, Column, Column> Udf<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>(...
* [x] `csharp` public static Func<Column> Udf(Func<Row> udf, StructType returnType)
* [x] `csharp` public static Func<Column, Column> Udf<T>(Func<T, Row> udf, StructType returnType)
* [x] `csharp` public static Func<Column, Column, Column> Udf<T1, T2>(...
* [x] `csharp` public static Func<Column, Column, Column, Column> Udf<T1, T2, T3>(...
* [x] `csharp` public static Func<Column, Column, Column, Column, Column> Udf<T1, T2, T3, T4>(...
* [x] `csharp` public static Func<Column, Column, Column, Column, Column, Column> Udf<T1, T2, T3, T4, T5>(...
* [x] `csharp` public static Func<Column, Column, Column, Column, Column, Column, Column> Udf<T1, T2, T3, T4, T5, T6>(...
* [x] `csharp` public static Func<Column, Column, Column, Column, Column, Column, Column, Column> Udf<T1, T2, T3, T4, T5, T6, T7>(...
* [x] `csharp` public static Func<Column, Column, Column, Column, Column, Column, Column, Column, Column> Udf<T1, T2, T3, T4, T5, T6, T7, T8>(...
* [x] `csharp` public static Func<Column, Column, Column, Column, Column, Column, Column, Column, Column, Column> Udf<T1, T2, T3, T4, T5, T6, T7, T8, T9>(...
* [x] `csharp` public static Func<Column, Column, Column, Column, Column, Column, Column, Column, Column, Column, Column> Udf<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(...
* [x] `csharp` public static Column CallUDF(string udfName, params Column[] columns)

**Comment by Niharikadutta** [comment]
I will work on this

**Comment by Niharikadutta** [comment]
All features associated with this issue have been merged, I think we can close this.

**Comment by Niharikadutta** [comment]
@imback82 @suhsteve I have exposed this API in #698  and verified there are no missing APIs as compared to `dataframe.py`

**Comment by Niharikadutta** [comment]
#698 has been merged, `DataFrame.ToJSON()` has been exposed, this issue can be closed.
