### ISSUE TITLE
[FEATURE REQUEST]: Spark 3.0 Readiness

### ISSUE THREAD

**Issue by suhsteve** [dotnet/spark#633]
# APIs

## SparkSession
* [x] `csharp` public static void SetActiveSession(SparkSession session) (#641)
* [x] `csharp` public static void ClearActiveSession() (#641)
* [x] `csharp` public static SparkSession GetActiveSession() (#641)
* [x] `csharp` public DataFrame ExecuteCommand(string runner, string command, Dictionary<string, string> options) (#647)

## DataFrame
* [x] `csharp` public DataFrame Transform(Func<DataFrame, DataFrame> func) (#688)
* [x] `csharp` public IEnumerable<Row> Tail(int n) (#647)
* [x] `csharp` public void PrintSchema(int level) (#647)
* [x] `csharp` public void Explain(string mode) (#647)
* [x] `csharp` public DataFrame Observe(string name, Column expr, params Column[] exprs) (#647)
* [x] `csharp` WriteTo(string table) (#677)

## DataFrameStatFunctions
* [x] `csharp` public DataFrame SampleBy<T>(Column column, IDictionary<T, double> fractions, long seed) (#647)

## DataFrameWriterV2
* [x] `csharp` public DataFrameWriterV2 Using(string provider) (#677)
* [x] `csharp` public DataFrameWriterV2 Option(string key, string value) (#677)
* [x] `csharp` public DataFrameWriterV2 Option(string key, bool value) (#677)
* [x] `csharp` public DataFrameWriterV2 Option(string key, long value) (#677)
* [x] `csharp` public DataFrameWriterV2 Option(string key, double value) (#677)
* [x] `csharp` public DataFrameWriterV2 Options(Dictionary<string, string> options) (#677)
* [x] `csharp` public DataFrameWriterV2 TableProperty(string property, string value) (#677)
* [x] `csharp` public DataFrameWriterV2 PartitionedBy(Column column, params Column[] columns) (#677)
* [x] `csharp` public void Create() (#677)
* [x] `csharp` public void Replace() (#677)
* [x] `csharp` public void CreateOrReplace() (#677)
* [x] `csharp` public void Append() (#677)
* [x] `csharp` public void Overwrite(Column condition) (#677)
* [x] `csharp` public void OverwritePartitions() (#677)

## RelationalGroupedDataset
* [ ] `scala` ~~def as[K: Encoder, T: Encoder]: KeyValueGroupedDataset[K, T]~~

## Functions
* [x] `csharp` public static Column XXHash64(params Column[] columns) (#649)
* [x] `csharp` public static Column Split(Column column, string pattern, int limit) (#649)
* [x] `csharp` public static Column Overlay(Column src, Column replace, Column pos, Column len) (#649)
* [x] `csharp` public static Column Overlay(Column src, Column replace, Column pos) (#649)
* [x] `csharp` public static Column AddMonths(Column startDate, Column numMonths) (#649)
* [x] `csharp` public static Column DateAdd(Column start, Column days) (#649)
* [x] `csharp` public static Column DateSub(Column start, Column days) (#649)
* [ ] `scala` ~~def transform(column: Column, f: Column => Column): Column~~ **Unsupported:** passing function as parameter
* [ ] `scala` ~~def transform(column: Column, f: (Column, Column) => Column): Column~~ **Unsupported:** passing function as parameter
* [ ] `scala` ~~def exists(column: Column, f: Column => Column): Column~~ **Unsupported:** passing function as parameter
* [ ] `scala` ~~def forall(column: Column, f: Column => Column): Column~~ **Unsupported:** passing function as parameter
* [ ] `scala` ~~def filter(column: Column, f: Column => Column): Column~~ **Unsupported:** passing function as parameter
* [ ] `scala` ~~def filter(column: Column, f: (Column, Column) => Column): Column~~ **Unsupported:** passing function as parameter
* [ ] `scala` ~~def aggregate(expr: Column, initialValue: Column, merge: (Column, Column) => Column, finish: Column => Column): Column~~ **Unsupported:** passing function as parameter
* [ ] `scala` ~~def aggregate(expr: Column, initialValue: Column, merge: (Column, Column) => Column): Column~~ **Unsupported:** passing function as parameter
* [ ] `scala` ~~def zip_with(left: Column, right: Column, f: (Column, Column) => Column): Column~~ **Unsupported:** passing function as parameter
* [ ] `scala` ~~def transform_keys(expr: Column, f: (Column, Column) => Column): Column~~ **Unsupported:** passing function as parameter
* [ ] `scala` ~~def transform_values(expr: Column, f: (Column, Column) => Column): Column~~ **Unsupported:** passing function as parameter
* [ ] `scala` ~~def map_filter(expr: Column, f: (Column, Column) => Column): Column~~ **Unsupported:** passing function as parameter
* [ ] `scala` ~~def map_zip_with(left: Column, right: Column, f: (Column, Column, Column) => Column): Column~~ **Unsupported:** passing function as parameter
* [x] `csharp` public static Column SchemaOfJson(Column json, Dictionary<string, string> options) (#649)
* [x] `csharp` public static Column MapEntries(Column column) (#649)
* [x] `csharp` public static Column FromCsv(Column column, StructType schema, Dictionary<string, string> options) (#649)
* [x] `csharp` public static Column FromCsv(Column column, Column schema, Dictionary<string, string> options) (#649)
* [x] `csharp` public static Column SchemaOfCsv(string csv) (#649)
* [x] `csharp` public static Column SchemaOfCsv(Column csv) (#649)
* [x] `csharp` public static Column SchemaOfCsv(Column csv, Dictionary<string, string> options) (#649)
* [x] `csharp` public static Column ToCsv(Column column, Dictionary<string, string> options) (#649)
* [x] `csharp` public static Column ToCsv(Column column) (#649)
* [x] `csharp` public static Column Years(Column column) (#649)
* [x] `csharp` public static Column Months(Column column) (#649)
* [x] `csharp` public static Column Days(Column column) (#649)
* [x] `csharp` public static Column Hours(Column column) (#649)
* [x] `csharp` public static Column Bucket(Column numBuckets, Column column) (#649)
* [x] `csharp` public static Column Bucket(int numBuckets, Column column) (#649)

**Comment by rrekapalli** [comment]
Is DataSet API also going to be part of this version?

**Comment by imback82** [comment]
@suhsteve Thanks for compiling this. Can you also compile the list from Scala as well?

**Comment by imback82** [comment]
@rrekapalli `Dataset` is not supported due to this: https://github.com/dotnet/spark/issues/103#issuecomment-491451584

We will not have a full MLLib as a part of 1.0.0, but we will track it separately in #381.

**Comment by rapoth** [comment]
CC: @GoEddie on the MLLib question in case he has more to add.

**Comment by GoEddie** [comment]
@rrekapalli I have been implementing the newer ML API (some internal classes are still MLLib), if you would like to contribute I am happy to help you with any pr’s. 

#381 is for ML.Features and then there is more as well after features.

**Comment by suhsteve** [comment]
@imback82 added the list of scala apis as well.

**Comment by rrekapalli** [comment]
@GoEddie , I am new to Spark and just trying out this library for one of my use case.  However, I can definitely give it a try from September 2nd week.

**Comment by Niharikadutta** [comment]
I'm thinking of dividing this into 3 PRs:

1. For `SparkSession`, `DataFrame` and `DataFrameStatFunctions` APIs
2. For `DataFrameWriterV2`
3. For `Functions` APIs

**Comment by Niharikadutta** [comment]
All features in this issue have been merged, this can be closed.
